trigger:
  - master
  - main

stages:
  # Build code
  - template: ./stages/build.yaml

  # Deploy code
  - template: ./stages/deploy.yaml
    parameters:
      azureSubscription: your-service-connection
      webServiceName: your-web-service-name
