stages:
  - stage: build
    displayName: Build azure.app.configuration.proxy

    jobs:
      - job: "build_and_publish_artifact"
        displayName: Build azure.app.configuration.proxy

        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - task: NodeTool@0
            retryCountOnTaskFailure: 1
            displayName: "Install Node.js"
            inputs:
              versionSpec: "17.x"

          - script: |
              npm install
              npm run build
            retryCountOnTaskFailure: 1
            displayName: "Install and build"

          - task: CopyFiles@2
            displayName: Move app files to artifact directory
            inputs:
              sourceFolder: $(System.DefaultWorkingDirectory)
              Contents: $(System.DefaultWorkingDirectory)/dist/**/*
              targetFolder: $(System.DefaultWorkingDirectory)/application-artifact
              overWrite: true

          # You need this in case you are running a web application on windows
          - task: CopyFiles@2
            displayName: Move web config to artifact directory
            inputs:
              sourceFolder: $(System.DefaultWorkingDirectory)
              Contents: $(System.DefaultWorkingDirectory)/web.config
              targetFolder: $(System.DefaultWorkingDirectory)/application-artifact
              overWrite: true

          - task: CopyFiles@2
            displayName: Move node modules to artifact directory
            inputs:
              sourceFolder: $(System.DefaultWorkingDirectory)
              Contents: $(System.DefaultWorkingDirectory)/node_modules/**/*
              targetFolder: $(System.DefaultWorkingDirectory)/application-artifact
              overWrite: true

          - task: ArchiveFiles@2
            displayName: Zip build artifacts
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)/application-artifact
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/azure-app-configuration-proxy.zip"
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/azure-app-configuration-proxy.zip
            displayName: Publish pipeline artifact
            artifact: azure-app-configuration-proxy
