parameters:
  - name: azureSubscription
    type: string

  - name: webServiceName
    type: string

stages:
  - stage: deploy
    displayName: Deploy application
    dependsOn: build

    jobs:
      - deployment: deploy
        displayName: Deploy azure.app.configuration.proxy

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: Download artifact
                  artifact: azure-app-configuration-proxy

                - task: AzureWebApp@1
                  displayName: Deploy to web service
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appName: ${{ parameters.webServiceName }}
                    package: $(Pipeline.Workspace)/azure-app-configuration-proxy/*.zip
